"""add photo_url to groups

Revision ID: 9063b316f0ea
Revises: 93e8a93afc4e
Create Date: 2025-09-02 10:54:20.266298
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9063b316f0ea"
down_revision = "93e8a93afc4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("photo_url", sa.String(), nullable=True))
    op.alter_column(
        "groups",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_constraint(op.f("groups_owner_id_fkey"), "groups", type_="foreignkey")
    op.add_column(
        "memberships",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_memberships_id"), table_name="memberships")
    op.drop_constraint(
        op.f("memberships_user_id_fkey"), "memberships", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("memberships_group_id_fkey"), "memberships", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "memberships", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "memberships", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("memberships", "role")
    op.drop_column("memberships", "joined_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memberships",
        sa.Column(
            "joined_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "memberships",
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "memberships", type_="foreignkey")
    op.drop_constraint(None, "memberships", type_="foreignkey")
    op.create_foreign_key(
        op.f("memberships_group_id_fkey"), "memberships", "groups", ["group_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("memberships_user_id_fkey"), "memberships", "users", ["user_id"], ["id"]
    )
    op.create_index(op.f("ix_memberships_id"), "memberships", ["id"], unique=False)
    op.drop_column("memberships", "created_at")
    op.create_foreign_key(
        op.f("groups_owner_id_fkey"), "groups", "users", ["owner_id"], ["id"]
    )
    op.alter_column(
        "groups",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("groups", "photo_url")
    # ### end Alembic commands ###
