"""add hashed_password to users

Revision ID: 93e8a93afc4e
Revises: a966d79daddb
Create Date: 2025-09-02 09:51:31.634127
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93e8a93afc4e"
down_revision = "a966d79daddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("users", sa.Column("photo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "photo_url")
    op.drop_column("users", "phone")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
